### PR TITLE
Release page

### PR DESCRIPTION
**Pull request by Storken**
## Description
Splits the css files into smaller chunks for maintainability.

The release page has been reworked to have a grid-style layout for the content instead of just rows of text.

### CODE REVIEW

**Comment by warpfork** [comment]
Okay, it's a little janky for me as yet...

In chromium:

**Comment by Storken** [comment]
> 

Hm, that's wierd, but great with a screenshot! I'll check it out

**Comment by Storken** [comment]
> Okay, it's a little janky for me as yet...
> 
> In chromium:
> 
> 

looks very broken, could you copy-pasta the html for me?

**Comment by warpfork** [comment]
Ouu, I think I see it.  There's a div tag on the wrong side of a loop close, somewhere.

```
<div class="tab-content">
	<div class="tab-content-grid">
		<div><strong>src</strong></div>
		<div class="short text-box">
			<span class="long-text">tar:5K7rekQyv4YJphfwfssRsLqHtrL4G9bVmCuarnJyvNaCWzABt6ujLvRRQ48ppRqvNZ</span>
			<button onclick="navigator.clipboard.writeText('tar:5K7rekQyv4YJphfwfssRsLqHtrL4G9bVmCuarnJyvNaCWzABt6ujLvRRQ48ppRqvNZ')">copy</button>
		</div>
		<div class="download-link"></div>
	</div> <!-- *** tab-content-grid ended already? *** -->
	
	<div><strong>amd64</strong></div>
	<div class="short text-box">
		<span class="long-text">tar:12KZBfkSbUHo9JJojPY7HHNP2FMobgTzoefARF2JkBo6KWj2E1mTquL4pfTAKtdfe6</span>
		<button onclick="navigator.clipboard.writeText('tar:12KZBfkSbUHo9JJojPY7HHNP2FMobgTzoefARF2JkBo6KWj2E1mTquL4pfTAKtdfe6')">copy</button>
	</div>
	<div class="download-link"></div>
</div>
```

(html grabbed from the inspector and then reformatted manually, hopefully without introducing more errors on the way...)

**Comment by Storken** [comment]
> 

oooooh, classic! 😄 should be fixed now!

**Comment by Storken** [comment]
Got these template-variables and things finally fixed! 

Screen Shot 2022-10-26 at 21 50 16

**Comment by Storken** [comment]
Ready for a review on this now 🙌

**Comment by warpfork** [comment]
Yeah, lgtm too! :D

**Pull request merged**
